# Generated by Django 5.1.3 on 2025-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_banners/",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_links",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Social Media Links"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="status_message",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Status Message"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default_profile_picture.jpg",
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
