# Generated by Django 5.1.3 on 2025-08-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_rename_group_admins_chat_group_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chats.message",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="group_image",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default_profile_picture.jpg",
                null=True,
                upload_to="chat_images/",
            ),
        ),
    ]
