# Generated by Django 5.1.3 on 2025-08-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_message_reply_to_alter_chat_group_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
