# Generated by Django 5.1.3 on 2025-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_message_delivered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
