# Generated by Django 5.1.3 on 2025-08-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="pinned_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chats.message",
            ),
        ),
    ]
