# Generated by Django 5.1.3 on 2025-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0010_poll_message_poll_polloption_pollvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[("image", "Image"), ("audio", "Audio"), ("file", "File")],
                default="file",
                max_length=10,
            ),
        ),
    ]
