# Generated by Django 5.1.3 on 2025-08-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0012_call"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Call",
        ),
    ]
