# Generated by Django 5.1.3 on 2025-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="iv",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.BinaryField(null=True),
        ),
    ]
